
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./platform/external-secrets/
  prune: true
  sourceRef:
    kind: ExternalArtifact
    name: cluster
  dependsOn:
    - name: cert-manager   # ðŸ‘ˆ reference by metadata.name of the other Kustomization
