
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway-install
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: cert-manager-config
  prune: false
  sourceRef:
    kind: ExternalArtifact
    name: cluster
  path: ./platform/envoy-gateway
