
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-install
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./platform/flux/
  prune: true
  sourceRef:
    kind: ExternalArtifact
    name: cluster
