---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-install
  namespace: flux-system
spec:
  interval: 10m0s
  prune: false
  sourceRef:
    kind: ExternalArtifact
    name: cluster
  path: ./platform/cert-manager/install
