---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-config
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./platform/cert-manager/config
  prune: true
  sourceRef:
    kind: ExternalArtifact
    name: cluster
  dependsOn:
    - name: cert-manager-install

